### ISSUE TITLE
How to read files ?

### ISSUE THREAD

**Issue by harrytrinh2** [zypp-io/azure-batch-load#46]
I am able to list a whole container with just the filenames as a dataframe. I also would like to read the content of files. How can I do that?

**Comment by erfannariman** [comment]
> 

@TrinhDinhPhuc you would need to download the files physically locally and then open them in some way to read the contents. You can use the [`Download`](https://github.com/zypp-io/azure-batch-load#2-using-methodsingle) class for the downloading part. The opening and reading content is not provided by this package, also since that can vary a lot depending on the type of file you have.

For example a csv file can be read with the native `csv` module in python or `pandas.read_csv`.

**Comment by erfannariman** [comment]
Closed for now since this is not perse package related, if you need any more help, feel free to comment
